[package]
name = "catboost-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catboost-sys = {git = "https://github.com/gagansingh894/catboost-sys.git"}